# Changes here will be overwritten by Copier
_commit: v1.3.4
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
include_notebooks: true
mypy_type_checking: none
package_name: hipscat
preferred_linter: pylint
project_license: BSD
project_name: hipscat
use_gitlfs: none
use_isort: true
