# Changes here will be overwritten by Copier
_commit: v1.2.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-calendar@googlegroups.com
author_name: LINCC Frameworks
create_example_module: false
module_name: hipscat
preferred_linter: pylint
project_name: hipscat
use_isort: true
