# Changes here will be overwritten by Copier
_commit: v1.5.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification:
- slack
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: hipscat
project_license: BSD
project_name: hipscat
project_organization: astronomy-commons
python_versions:
- '3.9'
- '3.10'
- '3.11'
